name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.13.4
  profanity_filter: ^2.0.0
  animated_text_kit: ^4.2.1
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  modal_progress_hud: ^0.1.3
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

